name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ÉTAPE 1 : Fixer Python sur la version stable 3.11 (Évite le bug Python 3.14)
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # ÉTAPE 2 : Installer JDK 17 (Requis pour l'API Android 34 et NDK r25b)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # ÉTAPE 3 : Installer les dépendances du système Ubuntu et de Python
      - name: Install System and Python Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          python -m pip install --upgrade "pip<24.1" "setuptools<70.0" "wheel<0.44"
          pip install --upgrade "python-for-android>=2024.1.21"
          pip install buildozer "cython>=3.0.0,<3.1.0"

           # ÉTAPE 4 : Configurer l'environnement Android et compiler l'APK
      - name: Build with Buildozer
        run: |
          mkdir -p -v $HOME/.android
          touch $HOME/.android/repositories.cfg
          # La ligne "buildozer android clean" a été supprimée d'ici pour éviter le crash
          buildozer -v android debug
        env:
          ACCEPT_SDK_LICENSE: "y"


      # ÉTAPE 5 : Sauvegarder l'APK généré pour le télécharger
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: bin/*.apk
